### ISSUE TITLE
Force quit as soon as it opens

### ISSUE THREAD

**Issue by smd75jr** [barmstrong/bitcoin-android#22]
I'm not sure if it's just me, but for some reason it force quits as soon as I try to open it on my Droid X

**Comment by brandoniles** [comment]
Thanks for the report, smd75jr.

It's likely being caused by a null pointer exception in BitcoinWallet.updateUI():

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitcoinandroid/com.bitcoinandroid.BitcoinWallet}: java.lang.NullPointerException
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
 at android.app.ActivityThread.access$1500(ActivityThread.java:123)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:130)
 at android.app.ActivityThread.main(ActivityThread.java:3835)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:507)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:847)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
 at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
 at com.bitcoinandroid.BitcoinWallet.updateUI(BitcoinWallet.java:133)             <--------------- Here.
 at com.bitcoinandroid.BitcoinWallet.onCreate(BitcoinWallet.java:67)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
 ... 11 more

**Comment by smd75jr** [comment]
how does one go about fixing it?

**Comment by stuhood** [comment]
After 10-30 seconds of a white screen, I also get dumped to a Force Quit box. HTC EVO 4G

**Comment by realhik** [comment]
I get the same immediate stack trace on my HTC desire. Starting bitcoin android is no longer possible.

**Comment by barmstrong** [comment]
We just published version 1.1 to the Android Market which attempts to fix it.  I say attempts because we don't have that exact hardware to test on.  I made an educated guess about what might be causing it but not 100% sure.  Can you let me know if this fixes it?

**Comment by smd75jr** [comment]
Nope still crashes on DROIDX. The report says something like
java.language.exception or soothing like that
On Jul 17, 2011 4:11 PM, "barmstrong" <
reply@reply.github.com>
wrote:

**Comment by huanix** [comment]
This issue just struck me today and has put my wallet into limbo. I have the same stack trace as the OP. I was tinkering with the app when it started - I sent 3 small transactions, then I set the device down with the camera barcode portion of the app running. I think my screen timed out, but I could still hear the camera trying to focus - so I turned the screen back on and the app began forceclosing. I tinkered with it awhile - long enough to realize that the prodnet.wallet file is overwritten each time you install the app (!?) -- now I'm just hoping I have an original copy of the file stored in a backup!

**Comment by huanix** [comment]
Good news! I have been working on this since this afternoon and I stumbled on a SIMPLE fix. I had a ROM Manager backup from the first day I installed bitcoin android; I was able to restore to that rom image and download the updated blockchain, then move my bitcoin out of the account. It may not work for everyone, but if you've got a recent backup you may be in luck!

**Comment by barmstrong** [comment]
Awesome!  Glad to hear that worked huanix!
